services:
  api:
    image: manhhiep2003/soinho-be
    container_name: api-container
    env_file:
      - .env.production.docker
    ports:
      - '${PORT}:${PORT}'
    depends_on:
      - postgres
    networks:
      - soinho

  postgres:
    image: postgres:15-alpine
    container_name: postgres-container
    env_file:
      - .env.production.docker
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - '5432:5432'
    networks:
      - soinho

networks:
  soinho:
    driver: bridge

volumes:
  postgres_data:
